CREATE TABLE IF NOT EXISTS partner_profiles (
  user_id BIGINT UNSIGNED NOT NULL,
  slug VARCHAR(191) NOT NULL,
  brand_name VARCHAR(100) NOT NULL,
  description TEXT NOT NULL,
  specializations_json TEXT NOT NULL,
  address TEXT NOT NULL,
  whatsapp VARCHAR(30) NOT NULL,
  instagram VARCHAR(191) NOT NULL DEFAULT '',
  tiktok VARCHAR(191) NOT NULL DEFAULT '',
  facebook VARCHAR(191) NOT NULL DEFAULT '',
  website VARCHAR(191) NOT NULL DEFAULT '',
  profile_photo_url VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  UNIQUE KEY partner_profiles_slug_unique (slug)
);

CREATE TABLE IF NOT EXISTS partner_gallery_items (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  title VARCHAR(100) NOT NULL,
  category VARCHAR(100) NOT NULL,
  image_url VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY partner_gallery_items_user_id_idx (user_id)
);

CREATE TABLE IF NOT EXISTS partner_packages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(100) NOT NULL,
  duration VARCHAR(100) NOT NULL,
  price BIGINT UNSIGNED NOT NULL,
  description TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY partner_packages_user_id_idx (user_id)
);
